import { History, LogOut, PackageCheck, PackagePlus, UserCircle2 } from "lucide-react";

import EmptyState from "../components/EmptyState";
import PageShell from "../components/PageShell";
import { useAppContext } from "../context/AppContext";

export default function ProfilePage({ onLogout }) {
  const { auth, foods, stats, userHistory } = useAppContext();

  const myDonations = foods.filter((food) => food.donor_id === auth.user.id);
  const pickupHistory = userHistory.filter((item) => item.action !== "food_added");
  const donationHistory = userHistory.filter((item) => item.action === "food_added");

  return (
    <PageShell
      eyebrow="Profile"
      title="Volunteer and donor profile"
      description="See your identity, personal contribution metrics, completed actions, and the activity history generated by the full ZeroWasteX workflow."
      action={
        <button
          type="button"
          onClick={onLogout}
          className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-semibold text-rose-600 shadow-lg transition hover:scale-[1.02]"
        >
          <LogOut className="h-4 w-4" />
          Logout
        </button>
      }
    >
      <section className="grid gap-6 lg:grid-cols-[0.95fr_1.05fr]">
        <div className="space-y-6">
          <article className="rounded-[1.75rem] border border-white/70 bg-white/80 p-6 shadow-xl shadow-slate-200/60 backdrop-blur">
            <div className="flex items-center gap-4">
              <div className="flex h-16 w-16 items-center justify-center rounded-3xl bg-teal-50 text-teal-700">
                <UserCircle2 className="h-9 w-9" />
              </div>
              <div>
                <h2 className="text-2xl font-semibold tracking-tight text-slate-950">{auth.user.name}</h2>
                <p className="text-sm text-slate-500">{auth.user.email}</p>
                <p className="mt-1 text-xs font-semibold uppercase tracking-[0.2em] text-teal-700">{auth.user.role}</p>
              </div>
            </div>
          </article>

          <div className="grid gap-5 md:grid-cols-3">
            <article className="rounded-[1.75rem] border border-white/70 bg-white/80 p-6 shadow-xl shadow-slate-200/60 backdrop-blur">
              <div className="flex items-center gap-3 text-slate-500">
                <PackageCheck className="h-5 w-5 text-teal-600" />
                Total pickups
              </div>
              <div className="mt-4 text-4xl font-semibold tracking-tight text-slate-950">{stats.myCompletedPickups}</div>
            </article>

            <article className="rounded-[1.75rem] border border-white/70 bg-white/80 p-6 shadow-xl shadow-slate-200/60 backdrop-blur">
              <div className="flex items-center gap-3 text-slate-500">
                <PackagePlus className="h-5 w-5 text-teal-600" />
                Total donations
              </div>
              <div className="mt-4 text-4xl font-semibold tracking-tight text-slate-950">{stats.myDonationCount}</div>
            </article>

            <article className="rounded-[1.75rem] border border-white/70 bg-white/80 p-6 shadow-xl shadow-slate-200/60 backdrop-blur">
              <div className="flex items-center gap-3 text-slate-500">
                <History className="h-5 w-5 text-teal-600" />
                Completed actions
              </div>
              <div className="mt-4 text-4xl font-semibold tracking-tight text-slate-950">{userHistory.length}</div>
            </article>
          </div>

          <article className="rounded-[1.75rem] border border-white/70 bg-white/80 p-6 shadow-xl shadow-slate-200/60 backdrop-blur">
            <h3 className="text-xl font-semibold tracking-tight text-slate-950">Donation history</h3>
            <div className="mt-4 space-y-3">
              {donationHistory.length === 0 ? (
                <div className="rounded-2xl bg-slate-50 px-4 py-4 text-sm text-slate-500">No donations published yet.</div>
              ) : (
                donationHistory.slice(0, 5).map((item) => (
                  <div key={item.id} className="rounded-2xl bg-slate-50 px-4 py-4">
                    <div className="font-medium text-slate-900">{item.message}</div>
                    <div className="mt-1 text-sm text-slate-500">{item.target?.food_name || "Food donation"}</div>
                  </div>
                ))
              )}
            </div>
          </article>

          <article className="rounded-[1.75rem] border border-white/70 bg-white/80 p-6 shadow-xl shadow-slate-200/60 backdrop-blur">
            <h3 className="text-xl font-semibold tracking-tight text-slate-950">Donation record</h3>
            <div className="mt-4 space-y-3">
              {myDonations.length === 0 ? (
                <div className="rounded-2xl bg-slate-50 px-4 py-4 text-sm text-slate-500">No donations published yet.</div>
              ) : (
                myDonations.slice(0, 5).map((food) => (
                  <div key={food.id} className="rounded-2xl bg-slate-50 px-4 py-4">
                    <div className="font-medium text-slate-900">{food.name}</div>
                    <div className="mt-1 text-sm text-slate-500">{food.quantity} | {food.status}</div>
                  </div>
                ))
              )}
            </div>
          </article>
        </div>

        <article className="rounded-[1.75rem] border border-white/70 bg-white/85 p-6 shadow-xl shadow-slate-200/60 backdrop-blur">
          <div className="flex items-center gap-3">
            <div className="rounded-2xl bg-teal-50 p-3 text-teal-700">
              <History className="h-5 w-5" />
            </div>
            <div>
              <h3 className="text-xl font-semibold tracking-tight text-slate-950">Pickup history</h3>
              <p className="text-sm text-slate-500">Requested food and completed pickups</p>
            </div>
          </div>

          <div className="mt-6 space-y-4">
            {pickupHistory.length === 0 ? (
              <EmptyState
                icon={History}
                title="No activity yet"
                description="Your request history will appear here once you start claiming pickups."
              />
            ) : (
              pickupHistory.map((item) => (
                <div key={item.id} className="rounded-2xl bg-slate-50 px-4 py-4">
                  <div className="font-medium text-slate-900">{item.message}</div>
                  <div className="mt-1 text-sm text-slate-500">{item.target?.food_name || "Food workflow event"}</div>
                  <div className="mt-2 text-xs font-semibold uppercase tracking-[0.2em] text-teal-700">
                    {item.action.replaceAll("_", " ")}
                  </div>
                </div>
              ))
            )}
          </div>
        </article>
      </section>
    </PageShell>
  );
}
